sudo: required
dist: trusty
language: node_js

services:

cache:
  directories:
    - node_modules

addons:
  chrome: stable

node_js:
  - "8"
  - "10"

matrix:
  fast_finish: true

before_install:
  - npm cache verify
  - npm prune
  - npm install -g @angular/cli

install:
  - npm install

script:
  - npm run build:ssr
  - npm run testServer
