sudo: required
dist: trusty
language: node_js

services:
  - docker

cache:
  directories:
    - node_modules

addons:
  chrome: stable

node_js:
  - "8"
  - "10"

matrix:
  fast_finish: true

before_install:
  - docker run -d -p 27017:27017 -v ~/data:/data/db mongo
  - npm cache verify
  - npm prune
  - npm install -g @angular/cli

install:
  - npm install

script:
  - npm run build:ssr
