sudo: required
dist: trusty
language: node_js

services:
  - docker

cache:
  directories:
    - node_modules

addons:
  chrome: stable

node_js:
  - "10"

matrix:
  fast_finish: true

before_install:
  - npm cache verify
  - npm prune
  - npm install -g @angular/cli

install:
  - npm install

jobs:
  include:
    - stage: Build
      script: npm run build:ssr
    - stage: Test
      script: npm run testServe
    - stage: Docker build
      script:
      - docker build -t $DOCKER_USERNAME/ahem .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $DOCKER_USERNAME/ahem
      - docker tag $DOCKER_USERNAME/ahem $DOCKER_USERNAME/ahem:$TRAVIS_BUILD_NUMBER
      - docker push $DOCKER_USERNAME/ahem

