sudo: required
dist: trusty
language: node_js

services:
  - docker

cache:
  directories:
    - node_modules

addons:
  chrome: stable

node_js:
  - "10"

matrix:
  fast_finish: true

before_install:
  - npm cache verify
  - npm prune
  - npm install -g @angular/cli

install:
  - npm install

script:
  - npm run build:ssr
  - npm run testServer

after_success:
  - docker build -t $DOCKER_USERNAM/ahem:$TRAVIS_BUILD_NUMBER .

deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/ahem
