sudo: required
dist: trusty
language: node_js

services:
  - mongodb

cache:
  directories:
    - node_modules

addons:
  chrome: stable

node_js:
  - "10"

matrix:
  fast_finish: true

before_install:
  - npm cache verify
  - npm prune
  - npm install -g @angular/cli

install:
  - npm install

jobs:
  include:
    - stage: "Build"
      script: npm run build:ssr
      name: "Build"
    - stage: "Tests"                # naming the Tests stage
      script: npm run testServer
      name: "Integration Tests"     # names the second Tests stage job
