version: "3"
services:
  ahem-ssr:
    image: o4oren/ahem-ssr:latest
    build:
      context: .
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "4000:3000"
    tty: true
    networks:
      - net1
    depends_on:
      - mongodb
    environment:
      - serverBaseUri=http://localhost:3000
      - mongoConnectUrl=mongodb://mongodb:27017/
      - appListenPort=3000
      - smtpPort=2525
      - allowAutocomplete=true
      - allowedDomains=my.domain.com
      - jwtSecret=AH3M 709 S3cR3T

  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - net1
networks:
  net1:

