version: "2"
services:
  ahem:
    container_name: ahem
    restart: "no"
    build: .
    logging:
      driver: syslog
      options:
        syslog-address: "udp://10.124.188.81:514"
    ports:
      - "3000:3000"
      - "25:25"
    tty: true
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"