apiVersion: v1
kind: Service
metadata:
  namespace: ahem
  name: ahem-mongo-cluster-ip-service
spec:
  ports:
      # service port in cluster
    - port: 27017
      # port to contact inside container
      targetPort: 27017
  selector:
    app: ahem-mongo
  type: ClusterIP
